language: node_js
node_js:
  - "0.10"

env: 
  global:
    - GRUNT_COMMAND=`./.travis/get_grunt_command.sh`
    - GRUNT_COMMAND2="build-test"

before_script:
 - gem install sass
 - npm install --verbose

script:
 - .travis/setup.sh
 - grunt $GRUNT_COMMAND2 --verbose
